# Generated by Django 4.1.3 on 2022-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.IntegerField(
                choices=[(0, "stuff"), (1, "student"), (2, "teacher")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
