# Generated by Django 4.1.3 on 2022-11-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_is_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="Talaba"),
        ),
    ]
