# Generated by Django 4.1.3 on 2022-11-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_is_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.IntegerField(
                choices=[(0, "stuff"), (1, "student"), (2, "sponsor")], default=0
            ),
        ),
    ]
