# Generated by Django 4.1.3 on 2022-11-25 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "1. Account"},
        ),
        migrations.RemoveField(
            model_name="account",
            name="date_modified",
        ),
        migrations.RemoveField(
            model_name="account",
            name="email",
        ),
        migrations.RemoveField(
            model_name="account",
            name="image",
        ),
        migrations.RemoveField(
            model_name="account",
            name="role",
        ),
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
        migrations.AddField(
            model_name="account",
            name="date_login",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan sanasi"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Male"), (2, "Female")],
                default=0,
                verbose_name="Jinsi",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_legal_entity",
            field=models.BooleanField(default=False, verbose_name="Yuridik shaxs"),
        ),
        migrations.AddField(
            model_name="account",
            name="is_physical_person",
            field=models.BooleanField(default=False, verbose_name="Jismoniy shaxs"),
        ),
        migrations.AlterField(
            model_name="account",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan sanasi"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="full_name",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 11, 25, 18, 32, 44, 815863, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
                verbose_name="Ism Familiya",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Admin"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Superuser"),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(
                db_index=True,
                default=1,
                help_text="(+998332150548)",
                max_length=13,
                unique=True,
                verbose_name="Telefon nomer",
            ),
            preserve_default=False,
        ),
    ]
