# Generated by Django 4.1.3 on 2022-11-25 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_alter_account_options_remove_account_date_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.RemoveField(
            model_name="account",
            name="full_name",
        ),
        migrations.AddField(
            model_name="account",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="accounts/",
                verbose_name="Account image",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="username",
            field=models.CharField(
                db_index=True,
                default=datetime.datetime(
                    2022, 11, 25, 19, 15, 18, 284533, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
                unique=True,
                verbose_name="Username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=13, unique=True, verbose_name="Telefon nomer"
            ),
        ),
    ]
