# Generated by Django 4.1.3 on 2022-11-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_account_options_remove_account_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(
                max_length=16, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
