# Generated by Django 4.1.3 on 2022-11-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_account_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="full_name",
            field=models.CharField(max_length=50, null=True, verbose_name="Full name"),
        ),
    ]
