# Generated by Django 4.1.3 on 2022-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_account_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_sponsor",
            field=models.BooleanField(default=False, verbose_name="Sponsor"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="Student"),
        ),
    ]
