# Generated by Django 4.1.3 on 2022-11-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentwallet_debt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentwallet",
            name="debt",
        ),
    ]
