# Generated by Django 4.1.3 on 2022-11-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_studentwallet_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentwallet",
            name="allocated_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
