# Generated by Django 4.1.3 on 2022-11-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "is_active": True,
                            "parent_category__isnull": True,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="university.otm",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTM",
                "verbose_name_plural": "OTM-lar",
            },
        ),
    ]
