# Generated by Django 4.1.3 on 2022-11-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_studentwallet_options"),
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OTM",
            new_name="University",
        ),
        migrations.AlterModelOptions(
            name="university",
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
            },
        ),
    ]
