# Generated by Django 4.1.3 on 2022-11-25 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor_wallet", models.FloatField(default=0.0)),
                ("spent_amount", models.FloatField(default=0.0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Process"),
                            (2, "Finished"),
                            (3, "Canceled"),
                        ],
                        default=0,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_sponsor": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Xomiylar",
                "verbose_name_plural": "Xomiylar",
            },
        ),
    ]
