# Generated by Django 4.1.3 on 2022-11-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsorwallet",
            options={"verbose_name": "Sponsor", "verbose_name_plural": "Sponsors"},
        ),
    ]
